### ISSUE TITLE
CaptchaBuilder::compression setting is never used

### ISSUE THREAD

**Issue by tedmielczarek-fastly** [samirdjelal/captcha-rs#10]
A very minor issue I noticed while reading the code. `CaptchaBuilder::build` doesn't use `self.compression` anywhere, it hard-codes the value `40`:
https://github.com/samirdjelal/captcha-rs/blob/07376c0b06d656a040f6098ea2a26cf9ac7972c9/src/lib.rs#L134

**Comment by samirdjelal** [comment]
Thanks for reporting, it is fixed now, will publish the new patch to crates.io in a min
